# Generated by Django 4.0.5 on 2023-06-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactHelp',
        ),
    ]
