# Generated by Django 4.0.5 on 2023-04-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0002_alter_quiz_difficulity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulity',
            field=models.CharField(choices=[('facile', 'Facile'), ('difficile', 'Difficile'), ('moyen', 'Moyen')], max_length=9),
        ),
    ]
