# Generated by Django 4.0.5 on 2023-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0004_alter_quiz_difficulity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulity',
            field=models.CharField(choices=[('moyen', 'Moyen'), ('facile', 'Facile'), ('difficile', 'Difficile')], max_length=9),
        ),
    ]
