# Generated by Django 4.0.5 on 2023-03-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helping',
            name='user',
        ),
    ]
