# Generated by Django 4.0.5 on 2023-03-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_remove_helping_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='helping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='help.helping'),
        ),
    ]
